import s1 from "./assets/images/s2.png";
const products = [
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Super Cake Lemon",
    link: "#",
    buttonColor: "bg-purple-600",
    buttonHoverColor: "purple-700",
    CustomBaclground: "#FE0002",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Super Cake Lemon",
    link: "#",
    buttonColor: "bg-sky-500",
    buttonHoverColor: "sky-700",
    CustomBaclground: "#FFE600",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Super Cake Lemon",
    link: "#",
    buttonColor: "bg-green-500",
    buttonHoverColor: "green-700",
    CustomBaclground: "#222584",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Description for Product 4",
    link: "#",
    buttonColor: "bg-yellow-500",
    buttonHoverColor: "yellow-700",
    CustomBaclground: "#FE0002",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Super Cake Lemon",
    link: "#",
    buttonColor: "bg-purple-600",
    buttonHoverColor: "purple-700",
    CustomBaclground: "#FE0002",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Super Cake Lemon",
    link: "#",
    buttonColor: "bg-sky-500",
    buttonHoverColor: "sky-700",
    CustomBaclground: "#FFE600",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Super Cake Lemon",
    link: "#",
    buttonColor: "bg-green-500",
    buttonHoverColor: "green-700",
    CustomBaclground: "#222584",
  },
  {
    imageUrl: s1,
    heading: "Super Cake Lemon",
    description: "Description for Product 4",
    link: "#",
    buttonColor: "bg-yellow-500",
    buttonHoverColor: "yellow-700",
    CustomBaclground: "#FE0002",
  },
];

export default products;
